Locales['id'] = {
    ['Pedagang']                   = 'Pedagang',
    ['Blip']                       = 'Kopi Secuan',
    ['cloakroom']                  = 'Tekan ~b~[E]~w~ untuk membuka Ruang Ganti',
    ['bossmenu']                   = 'Tekan ~b~[E]~w~ untuk membuka Boss Menu',
    ['inventory']                  = 'Tekan ~b~[E]~w~ untuk membuka Inventory Pedagang',
    ['cooking']                    = 'Tekan ~b~[E]~w~ untuk Memasak',
    ['distri']                     = 'Tekan ~b~[E]~w~ untuk membuka menu Distributor',
    ['quantity']                   = 'Jumlah',
    ['invalid_quantity']           = 'Jumlah Salah',
    ['have_deposited']             = 'Kamu menyimpan ~y~x%s~s~ ~b~%s~s~',
    ['have_withdrawn']             = 'Kamu mengambil ~y~x%s~s~ ~b~%s~s~',
    ['player_cannot_hold']         = 'Inventory kamu sudah ~r~penuh!',
    ['RecipeNotFound']             = 'Tidak menemukan resep dengan bahan itu!',
    ['RecipeNotEnough']            = 'Kamu tidak memiliki cukup bahan!',
    ['CookingSuccess']             = 'Berhasil memasak: ~y~',

    ['shop'] = 'shop',
	['shops'] = 'shops',
	['press_menu'] = 'press ~INPUT_CONTEXT~ to access the ~y~store~s~.',
	['bought'] = 'you just bought ~y~%sx~s~ ~b~%s~s~ for ~r~$%s~s~',
	['not_enough'] = 'you do not have ~r~enough~s~ money, you\'re ~y~missing~s~ ~r~$%s~s~!',
	['shop_confirm'] = 'buy %sx %s for $%s?',
	['no'] = 'no',
	['yes'] = 'yes',
    
}